#!/bin/bash
################################
#Purpose: To learn Until Loop
#Version: 1.0
#Owner 	: Kapil <kapil0123@gmail.com>
#Input	: None
#Output	: None
################################

NUM=1
until [ "$NUM" -gt 5 ]
do
echo "the num is $NUM"
NUM=`expr $NUM + 1`
done
