#!/bin/bash
################################
#Purpose: To install httpd with 
#	  firewalld exception
#Version: 1.0
#Owner 	: Kapil <kapil0123@gmail.com>
#Input	: None
#Output	: None
################################

echo "####### Script :: $0 STARTED #######..."
# Checking if firewalld package is installed
install_check()
{
        #echo "Enter the Package you want to install"
        #read PACK
        echo " this is the $PACK1 "
        exit
        rpm -q $PACK1
        if [ `echo $?` -eq 0 ]; then
        echo "$PACK1 is ALREADY installed!!!"

        else
        echo "###########Installing $PACK1 ...#################"
        sudo yum -y install $PACK1
        echo "##########installing $PACK1 completed############# "
        fi
}

PACK1=firewalld
install_check $PACK1
exit
httpd -v &> /dev/null

if [ "$?" -eq "0" ]; then
echo "httpd is ALREADY installed!!!"
else
echo "installing httpd ..."
sudo yum -y install httpd
echo "installing httpd completed "
fi
sleep 3
# checking if service is running of not
systemctl status httpd.service
if [ "$?" -eq "0" ]; then
echo "httpd is already RUNNING..."
else
COM=`systemctl start httpd.service`
echo "####### STARTING httpd sevice $COM #######"
fi

sleep 3
#check if starting at restart is enable or not
CHK=`sudo systemctl status httpd.service | awk '/disabled/ {print $NF}' `

if [ "$CHK" != "disabled)" ]; then
echo "#########httpd at is enabled at bootup#######"
else
echo "######httpd at bootup is disabled #######"
fi




