#!/bin/bash
# This scritp needs to be run after httpd is installed

## Checking for httpd is installed or not
httpd -v &> /dev/null
if [ ! "$?" -eq "0" ] ; then
echo " 1st Use firewall-httpd-install script to install httpd then run this script"
fi

## Installing PHP
php --version &> /dev/null
if [ ! "$?" -eq "0" ] ; then
echo " php is not installed so installing php"
sudo yum -y install php
fi

## Creating PHP test page
echo "Creating test page for PHP"
cd /var/www/html
touch dynamic.php
echo -e "<?php 
echo \""This is test php page"\";
date_default_timezone_set('Asia/Calcutta');
echo \" "Today is "\" . date(\""Y.m.d"\");
echo \"" The time is "\" . date(\""h:i:sa"\");
?>" > dynamic.php

echo "### END OF SCRIPT ###"
