#!/bin/bash
################################
#Purpose: To learn shell script
#Version: 1.0
#Owner 	: Kapil <kapil0123@gmail.com>
#Input	: None
#Output	: None
################################

echo "####### Script :: $0 STARTED #######..."
httpd -v

if [ "$?" -eq "0" ]; then
echo "httpd is ALREADY installed!!!"
else
echo "installing httpd ..."
sudo yum -y install httpd
echo "installing httpd completed "
fi

# checking if service is running of not
systemctl status httpd.service
if [ "$?" -eq "0" ]; then
echo "httpd is already RUNNING..."
else
COM=`systemctl start httpd.service`
echo "####### STARTING httpd sevice $COM #######"
fi






