#!/bin/bash
################################
#Purpose: To learn shell script
#Version: 1.0
#Owner 	: Kapil <kapil0123@gmail.com>
#Input	: None
#Output	: None
################################

echo "Enter software you want to install httpd"
read SOFT
rpm -qa | grep -i $SOFT

if [ "$?" -eq "0" ]; then
echo "$SOFT is ALREADY installed!!!"
else
echo "installing $SOFT ..."
sudo yum -y install $SOFT
echo "installing $SOFT completed "
fi

# checking if service is running of not
systemctl status httpd.service
if [ "$?" -eq "0" ]; then
echo "httpd is already RUNNING..."
else
COM=`systemctl start httpd.service`
echo "STARTING httpd sevice $COM "
fi






